FROM       ubuntu
MAINTAINER James Turnbull "james@example.com"
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
ENV REFRESHED_AT 2013-07-28
RUN apt-get update
